version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: 
      - "8081:80"
    depends_on:
      - postgres
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION=postgres://user:password@postgres:5432/crudapp
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crudapp
    volumes:
      - /e/Learning/basic-CRUD-app-on-k8s-project/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
