apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-frontend
  template:
    metadata:
      labels:
        app: crud-frontend
    spec:
      containers:
        - name: frontend
          image: lokiroo/crud-frontend:0.9
          ports:
            - containerPort: 80 
    